### ISSUE TITLE
Are 1 Hour bars  possible ? 

### ISSUE THREAD

**Issue by KristianOlser** [MatthiWare/YahooFinance.Core#14]
Hey i am desperate for 1 hour chart bars. This library only supports Daily,Weekly or Monthly. 
I would really need at least the 1 hours bars. Are there any limitation on the api, or what is the hiccup ?

Thanks in advance.

**Comment by Matthiee** [comment]
@KristianOlser No this library doesn't support hourly. 
Take a look at my other library [MatthiWare/FinancialModelingPrep.NET](https://github.com/MatthiWare/FinancialModelingPrep.NET) this one does have support for hourly bars.

**Comment by KristianOlser** [comment]
except it is paid. But thanks.
